variable "region_name" {
  description = "Value of AWS region"
  type        = string
  default     = "eu-central-1"
}

variable "your_first_name" {
  description = "User's first name"
  type        = string
  default     = "Stsiapan"
}

variable "your_last_name" {
  description = "User's last name"
  type        = string
  default     = "Prokasheu"
}

variable "generated_key_name" {
  description = "Key-pair generated by Terraform"
  type        = string
  default     = "ec2-ssh-key"
}

variable "ami_image" {
  description = "Ami image ID"
  type        = string
  default     = "ami-07df274a488ca9195"
}

variable "instance_type_size" {
  description = "Family and size of EC2 instance"
  type        = string
  default     = "t2.micro"
}



